# This is a basic workflow to help you get started with Actions

name: Pull Request Quality Checks

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: PR checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: Quality Checks
        run: |
          ls
          ls local-deps
          npm ci;
          npm run qa;
          npm run build;
          node .github/workflows/dependency-check.js;
